<a href="https://colab.research.google.com/github/joelhrtl/DataAnalysis/blob/main/Cereal_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cereal Project : Joel Hurtado - 20250310

In [ ]:
# import required (all) libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# upload excel file
from google.colab import files
uploaded = files.upload()

Saving cereal_data.xls to cereal_data.xls

In [ ]:
# read excel
df = pd.read_excel('cereal_data.xls')
df

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
0,Corn Chex,R,C,110.0,2.0,0.0,280.0,0.0,22.0,3.0,25.0,25.0,1.0,1.0,1.00,41.445019
1,Corn Flakes,K,C,100.0,2.0,0.0,290.0,1.0,21.0,2.0,35.0,25.0,1.0,1.0,1.00,45.863324
2,Rice Krispies,K,C,110.0,2.0,0.0,290.0,0.0,22.0,3.0,35.0,25.0,1.0,1.0,1.00,40.560159
3,Special K,K,NaN,110.0,6.0,0.0,230.0,1.0,16.0,3.0,55.0,25.0,1.0,1.0,1.00,53.131324
4,Multi-Grain Cheerios,G,C,100.0,2.0,1.0,220.0,2.0,15.0,6.0,90.0,25.0,1.0,1.0,1.00,40.105965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Grape Nuts Flakes,P,C,100.0,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,NaN,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.0,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.0,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.0,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [ ]:
# Display a summary of the basic information

In [ ]:
# df dimensions
df.shape

(77, 16)

In [ ]:
# df columns
df.columns

Index(['name', 'mfr', 'type', 'calories', 'protein', 'fat', 'sodium', 'fiber',
       'carbo', 'sugars', 'potass', 'vitamins', 'shelf', 'weight', 'cups',
       'rating'],
      dtype='object')

In [ ]:
# df information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      77 non-null     object
 1   mfr       73 non-null     object
 2   type      71 non-null     object
 3   calories  76 non-null     float64
 4   protein   76 non-null     float64
 5   fat       75 non-null     float64
 6   sodium    76 non-null     float64
 7   fiber     75 non-null     float64
 8   carbo     75 non-null     float64
 9   sugars    75 non-null     float64
 10  potass    76 non-null     float64
 11  vitamins  76 non-null     float64
 12  shelf     76 non-null     float64
 13  weight    74 non-null     float64
 14  cups      76 non-null     float64
 15  rating    77 non-null     float64
dtypes: float64(13), object(3)
memory usage: 9.8+ KB

In [ ]:
# Clean data-frame (df)

In [ ]:
# List of missing values by columns
df.isna().sum()

name        0
mfr         4
type        6
calories    1
protein     1
fat         2
sodium      1
fiber       2
carbo       2
sugars      2
potass      1
vitamins    1
shelf       1
weight      3
cups        1
rating      0
dtype: int64

In [ ]:
# select the num columns
num_cols = df.select_dtypes(include=np.number).columns
num_cols

Index(['calories', 'protein', 'fat', 'sodium', 'fiber', 'carbo', 'sugars',
       'potass', 'vitamins', 'shelf', 'weight', 'cups', 'rating'],
      dtype='object')

In [ ]:
# select cat columns
cat_cols = df.select_dtypes(include=object).columns
cat_cols

Index(['name', 'mfr', 'type'], dtype='object')

In [ ]:
# clean the num cols
for col in num_cols:
  df[col] = df[col].fillna(df[col].mean())

In [ ]:
# clean the cat cols
for col in cat_cols:
  df[col] = df[col].fillna(df[col].mode()[0])

In [ ]:
df.isna().sum()

name        0
mfr         0
type        0
calories    0
protein     0
fat         0
sodium      0
fiber       0
carbo       0
sugars      0
potass      0
vitamins    0
shelf       0
weight      0
cups        0
rating      0
dtype: int64

In [ ]:
# Print first and last six rows
df.head(6)
df.tail(6)

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
71,Golden Crisp,P,C,100.000000,2.0,0.0,45.0,0.0,11.0,15.0,40.0,25.0,1.0,1.0,0.88,35.252444
72,Grape Nuts Flakes,P,C,100.000000,3.0,1.0,140.0,3.0,15.0,5.0,85.0,25.0,3.0,1.0,0.88,52.076897
73,Rice Chex,R,C,106.842105,1.0,0.0,240.0,0.0,23.0,2.0,30.0,25.0,1.0,1.0,1.13,41.998933
74,Cheerios,G,C,110.000000,6.0,2.0,290.0,2.0,17.0,1.0,105.0,25.0,1.0,1.0,1.25,50.764999
75,Honey-comb,P,C,110.000000,1.0,0.0,180.0,0.0,14.0,11.0,35.0,25.0,1.0,1.0,1.33,28.742414
76,Kix,G,C,110.000000,2.0,1.0,260.0,0.0,21.0,3.0,40.0,25.0,2.0,1.0,1.50,39.241114

In [ ]:
# Find the minimum calories cereal name
min_cer_name = df[df["calories"] == df["calories"].min()]
min_cer_name

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
26,Puffed Rice,Q,C,50.0,1.0,0.0,0.0,0.0,13.0,0.0,15.0,0.000000,3.0,0.5,1.0,60.756112
27,Puffed Wheat,Q,C,50.0,2.0,0.0,0.0,1.0,10.0,0.0,50.0,0.000000,3.0,0.5,1.0,63.005645
39,All-Bran with Extra Fiber,K,C,50.0,4.0,0.0,140.0,14.0,8.0,0.0,330.0,28.289474,3.0,1.0,0.5,93.704912

In [ ]:
# Print the list of cereal name with sugar rate = 0
zero_sugars = df[df["sugars"] == 0][["name", "sugars"]]
zero_sugars

                         name  sugars
6      Cream of Wheat (Quick)     0.0
26                Puffed Rice     0.0
27               Puffed Wheat     0.0
28             Shredded Wheat     0.0
39  All-Bran with Extra Fiber     0.0
42  Shredded Wheat spoon size     0.0
43     Shredded Wheat 'n'Bran     0.0

In [ ]:
# Print the list of cereal name with the following four conditions:
cer_4conditions = df[ (df["calories"]> df["calories"].mean())
                    & (df["protein"]> df["protein"].mean())
                    & (df["carbo"]< df["carbo"].mean())
                    & (df["potass"]< df["potass"].mean())]
cer_4conditions

,name,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
57,Honey Nut Cheerios,G,C,110.0,3.0,1.0,250.0,1.5,11.5,10.0,90.0,25.0,1.0,1.0,0.75,31.072217

In [ ]:
# Print the minimum of "Vitamins_rate & sodium_rate" by cereal type
Tab1 = df.groupby("type")[["vitamins", "sodium"]].min().reset_index()
Tab1

  type  vitamins  sodium
0    C       0.0     0.0
1    H       0.0     0.0

In [ ]:
# Print the minimum of "Vitamins_rate & sodium_rate" by cereal typ & mfr
Tab2 = df.groupby(["type", "mfr"])[["vitamins", "sodium"]].min().reset_index()
Tab2

  type mfr  vitamins  sodium
0    C   G      25.0     0.0
1    C   K      25.0     0.0
2    C   N       0.0     0.0
3    C   P      25.0    45.0
4    C   Q       0.0     0.0
5    C   R      25.0    95.0
6    H   A      25.0     0.0
7    H   N       0.0    80.0
8    H   Q       0.0     0.0

In [ ]:
#Using a loop ( for... in..) to select a column names from a list of columns:
for col in num_cols:
  print(col)
  print("="* 12)
  print("The min of = ", df[col].min())
  print("The max of = ", df[col].max())
  print("****************************")

calories
============
The min of =  50.0
The max of =  160.0
****************************
protein
============
The min of =  1.0
The max of =  6.0
****************************
fat
============
The min of =  0.0
The max of =  5.0
****************************
sodium
============
The min of =  0.0
The max of =  320.0
****************************
fiber
============
The min of =  0.0
The max of =  14.0
****************************
carbo
============
The min of =  -1.0
The max of =  23.0
****************************
sugars
============
The min of =  -1.0
The max of =  15.0
****************************
potass
============
The min of =  -1.0
The max of =  330.0
****************************
vitamins
============
The min of =  0.0
The max of =  100.0
****************************
shelf
============
The min of =  1.0
The max of =  3.0
****************************
weight
============
The min of =  0.5
The max of =  1.5
****************************
cups
============
The min of =  0.25
The max of =  1.5
****************************
rating
============
The min of =  18.042851
The max of =  93.704912
****************************