<a href="https://colab.research.google.com/github/joelhrtl/DataAnalysis/blob/main/JobAdmission_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

import statsmodels.api as sm

In [30]:
# upload excel file
from google.colab import files
uploaded = files.upload()

Saving JOB_Admission.xlsx to JOB_Admission (1).xlsx

In [31]:
# Read excel file
import pandas as pd
df = pd.read_excel('JOB_Admission.xlsx')
df

,age,exam_score,experience,degree,extracurricular,internships,accepted
0,52,51,0,PhD,4,4,0
1,57,51,4,PhD,8,1,0
2,50,54,2,NaN,4,2,0
3,25,50,5,Master,0,2,0
4,56,58,4,Bachelor,2,2,0
...,...,...,...,...,...,...,...
95,37,92,15,Master,8,3,1
96,19,94,8,NaN,4,4,1
97,25,90,19,Master,9,2,1
98,28,98,6,NaN,9,3,1
99,26,98,17,NaN,7,1,1

In [32]:
#check missing values
df.isnull().sum()

age                 0
exam_score          0
experience          0
degree             28
extracurricular     0
internships         0
accepted            0
dtype: int64

In [33]:
df.shape

(100, 7)

In [34]:
# Clean degree column by replace missing values by the mode
df['degree'] = df['degree'].fillna(df['degree'].mode()[0])
df.isna().sum()

age                0
exam_score         0
experience         0
degree             0
extracurricular    0
internships        0
accepted           0
dtype: int64

In [35]:
df.columns

Index(['age', 'exam_score', 'experience', 'degree', 'extracurricular',
       'internships', 'accepted'],
      dtype='object')

In [36]:
# SELECT X  FUTURES
x=df[['age', 'exam_score', 'experience', 'degree', 'extracurricular', 'internships']]
x.head()

   age  exam_score  experience    degree  extracurricular  internships
0   52          51           0       PhD                4            4
1   57          51           4       PhD                8            1
2   50          54           2       PhD                4            2
3   25          50           5    Master                0            2
4   56          58           4  Bachelor                2            2

In [37]:
#SELECT TARGET
x ["degree"] = x["degree"].map({'PhD' : 3, 'Master' : 2, 'Bachelor' : 1 })
x
y = df['accepted']

/tmp/ipykernel_148/3967588993.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x ["degree"] = x["degree"].map({'PhD' : 3, 'Master' : 2, 'Bachelor' : 1 })

In [44]:
# Split data frame
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [45]:
#Scaling Data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [46]:
# Build the ML Model (log rate)
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [47]:
# Predict Y test
y_pred = model.predict(x_test)
y_pred

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [48]:
y_test.tolist()

[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0]

In [56]:
# Evaluate Model's Accuracy
metrics.accuracy_score(y_test, y_pred)

0.95